Scriptname ARM_ObjectHolder  Hidden 
{Script that holds all necessary forms for the DLL to function.}

;/
Alchemy
/;
Formlist Property ARM_Alchemy_FRL_UnCommonIngredients Auto
Formlist Property ARM_Alchemy_FRL_RareIngredients Auto
Formlist Property ARM_Alchemy_FRL_UniqueIngredients Auto

MagicEffect Property ARM_Alchemy_MGF_SlowDeathEffectFFSelf Auto 
MagicEffect Property ARM_Alchemy_MGF_LastingTreatmentHealthFFSelf Auto 
MagicEffect Property ARM_Alchemy_MGF_LastingTreatmentStaminaFFSelf Auto 
MagicEffect Property ARM_Alchemy_MGF_LastingTreatmentMagickaFFSelf Auto 

Perk Property ARM_Alchemy_PRK_050_QualityIngredients Auto
Perk Property ARM_Alchemy_PRK_080_SlowDeath Auto
Perk Property ARM_Alchemy_PRK_080_Stimulants Auto

;/
Armor
/;
Perk Property ARM_Armor_PRK_070_CombatRush Auto
Perk Property ARM_Armor_PRK_100_Unbreakable Auto

Spell Property ARM_Armor_SPL_CombatRushProc Auto

Keyword Property ARM_Armor_KWD_ArmorTypeHeavyCuirass Auto
Keyword Property ARM_Armor_KWD_ArmorTypeLightCuirass Auto

;/
Conjuration
/;
MagicEffect Property ARM_Conjuration_MGF_DeadlyPremonitionFFAimed Auto
MagicEffect Property ARM_Conjuration_MGF_DeadlyPremonitionFFContact Auto
MagicEffect Property ARM_Conjuration_MGF_DeadlyPremonitionFFTActor Auto